### ISSUE TITLE
Real ads not showing but test ads are

### ISSUE THREAD

**Issue by sushilbalami** [bdlukaa/native_admob_flutter#10]
Real ads shows on emulator but doesnt shows on the real device. Why so ?
Actually, real devices show test ads, but real ad doesnt seems to be showing.

**Comment by bdlukaa** [comment]
Since emulator are automatically considered as test devices, they will only get test ads. You can see here the possible reason of the ads not showing: https://support.google.com/admob/answer/9469204?hl=en

But I'll leave here the possible reason:
> When you first sign up for AdMob, your account is reviewed before it’s approved. This typically takes up to 24 hours, but in rare cases can take up to 2 weeks.

> Newly registered apps and newly created ad units typically take up to an hour to activate.

**Comment by bdlukaa** [comment]
Hello @sushilbalami . Can you try this plugin in a newly created project? Some users have notice that projects created before flutter version 1.22 have some issues. See [this](https://github.com/bdlukaa/native_admob_flutter/wiki/Platform-setup#flutter)

**Comment by SureshKumar311** [comment]
> Since emulator are automatically considered as test devices, they will only get test ads. You can see here the possible reason of the ads not showing: https://support.google.com/admob/answer/9469204?hl=en
> 
> But I'll leave here the possible reason:
> 
> > When you first sign up for AdMob, your account is reviewed before it’s approved. This typically takes up to 24 hours, but in rare cases can take up to 2 weeks.
> 
> > Newly registered apps and newly created ad units typically take up to an hour to activate.



i had try in both emulator and mobile but same error the real ads r not working

**Comment by SureshKumar311** [comment]
@bdlukaa 
hello i had got very confused and i had check u example app from 
now i had used your example app to test my admob real ads 

```void main() async {
  /// Make sure you add this line here, so the plugin can access the native side
  WidgetsFlutterBinding.ensureInitialized();

  /// Make sure to initialize the MobileAds sdk. It returns a future
  /// that will be completed as soon as it initializes
  await MobileAds.initialize(
      interstitialAdUnitId: 'ca-app-pub-28205****37/3641**46',
      nativeAdUnitId: 'ca-app-pub-2820502455308437/9671****78',
      bannerAdUnitId: 'ca-app-pub-282050****3425');
  // This is my device id. Ad yours here
  //MobileAds.setTestDeviceIds(['9345804C1E5B8F0871DFE29CA0758842']);

  /// Run the app
  runApp(MyApp());
}```

wheather i had add ad uint id in other field link

```  final controller = NativeAdController(unitId: ??????????);
```

i had add AndroidManifest
``` 
<meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-2820*****08437~904***08392"/>
```

error on example app 
```
D/DynamitePackage(32683): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
I/Ads     (32683): Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("803137889471BFC07C5A5B6FF8AB8630")) to get test ads on this device.
I/DynamiteModule(32683): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:210890500
I/DynamiteModule(32683): Selected remote version of com.google.android.gms.ads.dynamite, version >= 210890500
I/DynamiteModule(32683): Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:210890500
I/DynamiteModule(32683): Selected remote version of com.google.android.gms.ads.dynamite, version >= 210890500
2
D/AudioManager(32683): getStreamVolume isRestricted mode = 0
I/Ads     (32683): Ad failed to load : 3

```

so please help me i am beginer too and check my code
i need to reminder u as app  was not published and not link with firebase too 
i had try different admob accounts but still same

**Comment by bdlukaa** [comment]
If you are running in debug mode, you must add that test device code in that line you commented:
 `MobileAds.setTestDeviceIds([803137889471BFC07C5A5B6FF8AB8630]);`

To test your real ads, run `flutter run --release`, but comment the line above

**Comment by bdlukaa** [comment]
> I/Ads     (32683): Ad failed to load : 3

According to [wiki/Ad error codes](https://github.com/bdlukaa/native_admob_flutter/wiki/Ad-error-codes#load-error-codes), the request was successful, but no ad was returned due to lack of ad inventory.

That means this is not a problem with the implementation, but with the server.

**Comment by SureshKumar311** [comment]
hi guys 
I had found an idea to solve an issue 
the test is working fine but real ads are stopped or not served to our app 
so we need to upload our app in any admob recommended store play store or mi store or others to solve this problem

I had uploaded my app to mi store after it was accepted or goes live in mi store The ads are working fine
