### ISSUE TITLE
Use RequestContiguration.Builder().setTestDeviceIds() to get test ads on this device.

### ISSUE THREAD

**Issue by EternalYouth29** [bdlukaa/native_admob_flutter#100]
Test ads were working well, but last night I started getting this log message,
```
Ad failed to load : 3
I/Ads     ( 5394): Use RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("4EA173......27")) to get test ads on this device.
```
Cant get any test ads (both NativeAds and BannerAds) since then.  So far this happens only on `Android`.

**Comment by EternalYouth29** [comment]
> 
> 
> You can set the test device id using `MobileAds.setTestDeviceIds(['4EA173......27'])`
> 
> https://github.com/bdlukaa/native_admob_flutter/wiki/Initialize#add-your-test-device-programmatically

Thanks for the guidance. I have added so but this issue happens again. I am getting `Ad failed to load : 3` error message.  
But on iOS everything is working fine, it only happens on Android. And It has been a week. Now I am not able to design the ads layout😥

**Comment by desmeit** [comment]
Where can I find the device id of my Android phone?
