### ISSUE TITLE
Name conflict of between "google_mobile_ads.dart" and "native_admob_flutter"

### ISSUE THREAD

**Issue by itsmegeekysharma** [bdlukaa/native_admob_flutter#102]
When trying to implement BannerAd() widget VS Code shows ...

![image](https://user-images.githubusercontent.com/89698492/132132462-ed88f111-6c0d-4be2-90eb-b7fc83179a31.png)

Now tell me what to do.

**Comment by bdlukaa** [comment]
https://github.com/flutter/flutter/issues/34395
