### ISSUE TITLE
The ads I implemented do not show up in AppReview.

### ISSUE THREAD

**Issue by kokikudo** [bdlukaa/native_admob_flutter#116]
Help me, please!

I'm implementing banner ads and native ads in my app, but it's not passing Apple Review.

There are two problem areas that Apple has sent me. 

1. The ads are not showing up.
I've implemented banner ads at the bottom of the screen, but I've received reports that they are not showing up.
However, in my emulator, they are displayed without any problem.

2. App Tracking Transparency permission request is not displayed.
This also appears fine in my emulator.

The emulator is IOS15.0, but AppReview seems to be reviewing it on IOS15.1.
Have you confirmed the issue of ads not showing up in IOS15.1?

Translated with www.DeepL.com/Translator (free version)

**Comment by bdlukaa** [comment]
Ads usually show up when the app is published to the store

**Comment by kokikudo** [comment]
I just checked AppStoreConnect and it has been reviewed which was rejected.
I don't know why.
But thank you for your help!
