### ISSUE TITLE
[Feature Request] Mute ads at app level

### ISSUE THREAD

**Issue by nathan1658** [bdlukaa/native_admob_flutter#128]
The official google_mobile_ads have a feature of **MobileAds.instance.setAppMuted(true);**, Is there a similar way to archive the same stuff with this library? It would be great to have this feature for this library.
I've came across multiple flutter ads library and for me this is the best one, much better performance then the official google_mobile_ads, amazing work!

**Comment by bdlukaa** [comment]
https://github.com/bdlukaa/native_admob_flutter/blob/master/lib/src/mobile_ads.dart#L312

`MobileAds.setAppMuted(true)`

or

`MobileAds.setVolume(<volume>)`

**Comment by nathan1658** [comment]
> 



> https://github.com/bdlukaa/native_admob_flutter/blob/master/lib/src/mobile_ads.dart#L312
> 
> `MobileAds.setAppMuted(true)`
> 
> or
> 
> `MobileAds.setVolume(<volume>)`

Sorry for overlooking it. Appreciated it!
