### ISSUE TITLE
Warning from google: Not all asset views lie inside the native ad view.

### ISSUE THREAD

**Issue by DevKathirva** [bdlukaa/native_admob_flutter#13]
> I/Ads     ( 4249): Received log message: <Google:HTML> Not all asset views lie inside the native ad view. This indicates an integration problem. Such implementations will not be supported in the future. Please make sure that all native ad assets are rendered inside the native ad view.

Getting this log message with the example code.

**Comment by bdlukaa** [comment]
Make sure the whole content from the NativeAd is rendered inside the rendering area, that means there can't be any clipping nor drawings over.

If that doesn't solve your issue, please give me more details. If it does, please close the issue :)

**Comment by DevKathirva** [comment]
My mistake was I gave wrap_content to media height. It should be fixed height as mentioned in the example.
