### ISSUE TITLE
[QUESTION] Is it necessary to show the openAppAd from the splash screen?

### ISSUE THREAD

**Issue by comlaterra** [bdlukaa/native_admob_flutter#130]
There are many discussions around what is a "Disruptive Ad".
Until the point where we could think that it is required to show the Open App ad from the splash screen.

Despite in the google documentation we can see in many places that they mention a "loading screen", it is not clear if they are talking about the Splash screen or a screen shown by ( in this case ) Flutter, and so it is shown *after* the splash screen.

Can you clarify if that's the case?

Thanks!

**Comment by bdlukaa** [comment]
When you navigate from one screen to another, for example, while loading data, could be a place to show the open app ad. It's not recommended to show ads on startup since it's not a good user experience!

**Comment by comlaterra** [comment]
Your answer is slightly confusing 😅  The openApAdd is meant to monetize the loading screen.... on open app 🤷 

So in the [App open ad guidance](https://support.google.com/admob/answer/9341964?hl=en ) we can see one example of implementation.
In the Mobile SDK page we can find an"explanation" ( but not example ) on how to implement this: [here](https://developers.google.com/admob/android/app-open#coldstart)

I see, now I think I understand, so despite it is explained how to do it: https://developers.google.com/admob/flutter/app-open ( but no example anywhere ) and
