### ISSUE TITLE
Cannot find 'kGADAdSizeBanner' in scope

### ISSUE THREAD

**Issue by erperejildo** [bdlukaa/native_admob_flutter#133]
I'm getting this issue that stops me from compiling on iOS. Using 1.5.0.

Android is fine

**Comment by wonpyohong** [comment]
same issue

**Comment by yusriltakeuchi** [comment]
Same issue

**Comment by ahde46** [comment]
same issue here

**Comment by erperejildo** [comment]
@bdlukaa any update about this?

**Comment by yusriltakeuchi** [comment]
Maybe someone can fix this issue and put into new git repository.
I think the author is really busy...

**Comment by erperejildo** [comment]
> Maybe someone can fix this issue and put into new git repository. I think the author is really busy...

maybe this comment helps?

https://stackoverflow.com/a/71035981/4858133

**Comment by erperejildo** [comment]
> Maybe someone can fix this issue and put into new git repository. I think the author is really busy...

This is blocking my iOS update. Don't mind to hear that but at least something just to know I can wait or not

**Comment by bdlukaa** [comment]
Hello! Please, see #58. I don't have a mac neither an iphone to give you support. All the ios support come from the community

**Comment by erperejildo** [comment]
I asked the question there but not having a iOS support is a really negative point IMO

**Comment by yusriltakeuchi** [comment]
@erperejildo hey bro, maybe you can try this solution, it's work for me.
But i hope the author will updating this issue.

In native_admob_flutter/ios/Classes/Banner/BannerAdView.swift line 9:
try change from:
```dart
private var adSize: GADAdSize = kGADAdSizeBanner
```

to :
```dart
private var adSize: GADAdSize = GADAdSizeFromCGSize(CGSize(width: 320, height: 100))
```

This is just create a default adSize when you're not inserting custom size.
The condition can be found in line 38

**Comment by erperejildo** [comment]
thanks for that @yusriltakeuchi. I see that it's merged already

**Comment by erperejildo** [comment]
@bdlukaa any plan to release this soon?

**Comment by felixgabler** [comment]
Hi, my app release is also blocked because of this issue. Could you please release another update? 🙏

**Comment by bdlukaa** [comment]
You can use the master branch as your dependencies:

```yaml
dependencies:
  native_admob_flutter:
    git: https://github.com/bdlukaa/native_admob_flutter.git
```

**Comment by erperejildo** [comment]
> You can use the master branch as your dependencies:
> 
> ```yaml
> dependencies:
>   native_admob_flutter:
>     git: https://github.com/bdlukaa/native_admob_flutter.git
> ```

why not releasing a new version?

**Comment by naamapps** [comment]
Facing this issue too.
@bdlukaa please deploy to pub.dev.
Using the git dependency is not the best practice.

**Comment by erperejildo** [comment]
can we open this issue again until it is deployed please?
