### ISSUE TITLE
Request to add a way to set Ad Unit ID for Native Ads

### ISSUE THREAD

**Issue by nemoryoliver** [bdlukaa/native_admob_flutter#14]
Currently, I don't see a way to do it. Thanks again for developing this great pugin!

**Comment by bdlukaa** [comment]
- You can set them when initializing. See [Initializing](https://github.com/bdlukaa/native_admob_flutter/wiki/Initialize#initialize-the-mobile-ads-sdk).
- You can use a controller to set your own unit id to load the ads. See [Using the controller](https://github.com/bdlukaa/native_admob_flutter/wiki/Using-the-controller-and-listening-to-native-events#reloading-the-ad)

On the next version, there'll be a parameter called `unitId` in the `NativeAd` constructor.

**Comment by nemoryoliver** [comment]
> * You can set them when initializing. See [Initializing](https://github.com/bdlukaa/native_admob_flutter/wiki/Initialize#initialize-the-mobile-ads-sdk).
> * You can use a controller to set your own unit id to load the ads. See [Using the controller](https://github.com/bdlukaa/native_admob_flutter/wiki/Using-the-controller-and-listening-to-native-events#reloading-the-ad)
> 
> On the next version, there'll be a parameter called `unitId` in the `NativeAd` constructor.

Sorry I forgot to mention specifically to set ad unit ids individually. But thanks for pointing out it's possible via Controller. Would be great if you could just set it in it's widget parameter though.

**Comment by bdlukaa** [comment]
> Would be great if you could just set it in it's widget parameter though.

I just published a new version that adds this possibility: [v0.9.3](https://pub.dev/packages/native_admob_flutter)

**Comment by nemoryoliver** [comment]
> > Would be great if you could just set it in it's widget parameter though.
> 
> I just published a new version that adds this possibility: [v0.9.3](https://pub.dev/packages/native_admob_flutter)

Great update! thank you
