### ISSUE TITLE
1.0.0-pre BannerAds not showing on iOS with real adUnitIDs

### ISSUE THREAD

**Issue by ad-on-is** [bdlukaa/native_admob_flutter#21]
While BannerAds are shown when using test unit ids, they are not shown when using real ad units.

```
iOS Admob status: ["GADMobileAds": <GADAdapterStatus: 0x280717ed0; state = Ready>]
<Google> Invalid Request. Too many recently failed requests for ad unit ID: ca-app-pub-XXX/YYY. You must wait a few seconds before making another ad request.
```

**Comment by bdlukaa** [comment]
Can you please listen to events using the controller and print the error? [Learn more](https://github.com/bdlukaa/native_admob_flutter/wiki/Using-the-controller-and-listening-to-banner-events#listening-to-events)

You can see the error codes [here](https://github.com/bdlukaa/native_admob_flutter/wiki/Ad-error-codes)

**Comment by ad-on-is** [comment]
```dart
BannerAdController controller = BannerAdController();
 @override
  void initState() {
    print('AD INITED');
    controller.onEvent.listen((e) {
      final event = e.keys.first;
      switch (event) {
        case BannerAdEvent.loading:
          print('loading');
          break;
        case BannerAdEvent.loaded:
          print('loaded');
          break;
        case BannerAdEvent.loadFailed:
          final errorCode = e.values.first;
          print('loadFailed $errorCode');
          break;
        default:
          break;
      }
    });
    super.initState();
  }
```


```
iOS Admob status: ["GADMobileAds": <GADAdapterStatus: 0x2806aaca0; state = Ready>]
flutter: AD INITED
flutter: AD INITED
flutter: AD INITED
flutter: loading
flutter: loading
flutter: loading
flutter: loadFailed #-1: Timeout achieved
```

**Comment by bdlukaa** [comment]
The ad took more than 30 seconds to load and a timeout error was thrown. You can try increasing the timeout using the `timeout` property in the Banner Ad Constructor

**Comment by ad-on-is** [comment]
I did not provide `MobileAds.setTestDeviceIds()`, but now since I've done that, BannerAds on iOS are loading instantly. But why didn't they work without the testId? Or is this intended behaviour?

**Comment by bdlukaa** [comment]
> But why didn't they work without the testId?

Usually this happens when:
1. your account is too new: it needs to be approved before you can receive any ads using your unit id. You'll receive an email when your account gets approved or not;
2. your unit id was recently created: it can take up to 24 hours (it's normally 2-3 hours) to start receiving ads

> Although the BannerAd is showing, I still get the Timeout achieved warning

This is a known issue and will be fixed in the next version. See https://github.com/bdlukaa/native_admob_flutter/issues/19

**Comment by ad-on-is** [comment]
Ah ok, thx for clarification (y)
Great package btw... keep up the good work ;-)

**Comment by bdlukaa** [comment]
Thank you very much :)

Can this be closed?

**Comment by ad-on-is** [comment]
Sure! 👍
