### ISSUE TITLE
IOS IDFA: Unsupported value: __C.ATTrackingManagerAuthorizationStatus of type __SwiftValue

### ISSUE THREAD

**Issue by sharokh1** [bdlukaa/native_admob_flutter#23]
If I add `final TrackingAuthorizationStatus status = await MobileAds.requestTrackingAuthorization();`
my app will crash

This is the crash log

`Unsupported value: __C.ATTrackingManagerAuthorizationStatus of type __SwiftValue
*** Assertion failure in -[FlutterStandardWriter writeValue:], FlutterStandardCodec.mm:330
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unsupported value for standard codec'
*** First throw call stack:
(0x18f18d86c 0x1a41a8c50 0x18f093000 0x19042791c 0x103f43098 0x103f4010c 0x103057fe8 0x103076954 0x103076a00 0x1c11fbb7c 0x1030762f0 0x103076bf8 0x103f40074 0x1036dfb78 0x1039def5c 0x10397e35c 0x103980a14 0x18f109fa0 0x18f109ba0 0x18f108ffc 0x18f102ee4 0x18f10221c 0x1a6cce784 0x191b42ee8 0x191b4875c 0x102e58378 0x18edc26b0)
libc++abi.dylib: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001bd0e2414 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1bd0e2414 <+8>:  b.lo   0x1bd0e2434               ; <+40>
    0x1bd0e2418 <+12>: pacibsp
    0x1bd0e241c <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1bd0e2420 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
`

**Comment by bdlukaa** [comment]
Fixed in [v1.0.1](https://pub.dev/packages/native_admob_flutter)
