### ISSUE TITLE
[Event] Not found click event

### ISSUE THREAD

**Issue by phanvanluan94** [bdlukaa/native_admob_flutter#26]
Is this event removed? I can not find it to use. 

<img width="415" alt="Screen Shot 2021-03-12 at 20 34 29" src="https://user-images.githubusercontent.com/22259333/110947135-5a559280-8372-11eb-8a6c-b67090ab73cc.png">

And seems this event is not supported by other kinds of ad also.
Thanks for this great plugin.

**Comment by phanvanluan94** [comment]
Yes, currently I handled some conditions to prevent users from abusing ad. 
I am very happy if it is added again. Thank you.

**Comment by bdlukaa** [comment]
Well, according to [the official documentation](https://developers.google.com/admob/android/banner#ad_events), `onAdClicked` is not an event, so you'll never receive it. The same for [iOS](https://developers.google.com/admob/ios/banner#ad_events)

**Comment by phanvanluan94** [comment]
> Well, according to [the official documentation](https://developers.google.com/admob/android/banner#ad_events), `onAdClicked` is not an event, so you'll never receive it. The same for [iOS](https://developers.google.com/admob/ios/banner#ad_events)

I think that it might be an event to check when the user leaving the application. I hope the below link could help.
https://github.com/googleads/googleads-mobile-flutter#banner-ad-events

**Comment by bdlukaa** [comment]
Yes, there it, but I didn't think it was necessary. I'll add it in the next release :)

**Comment by phanvanluan94** [comment]
It would be great.
Thank you.

**Comment by bdlukaa** [comment]
`leftApplication` was added in version [1.0.2+1](https://pub.dev/packages/native_admob_flutter).
