### ISSUE TITLE
Native ad is not shown if the controller is loaded before creating NativeAd widget

### ISSUE THREAD

**Issue by shimaatech** [bdlukaa/native_admob_flutter#27]
The following code doesn't work and shows the loading placeholder always:
```
if (controller.isLoaded) {
  return NativeAd(...);
}

```
it's because of the following line in native_ad_widget.dart

`if (state == NativeAdEvent.loading) return widget.loading ?? SizedBox();`

**Comment by bdlukaa** [comment]
Fixed in version [1.1.0](https://pub.dev/packages/native_admob_flutter)
