### ISSUE TITLE
SetAppVolume crash in ios

### ISSUE THREAD

**Issue by nickgoh** [bdlukaa/native_admob_flutter#29]
when using setAppVolume, crash during app launch

MobileAds.setAppVolume(0.5);

**Error in IOS :**
https://github.com/bdlukaa/native_admob_flutter/blob/d00dd7eb88c77f57fa3924c3d3c6a0cd169d7cd5/ios/Classes/NativeAdmobFlutterPlugin.swift#L130

Fatal error: Unable to bridge NSNumber to Float: file Foundation/NSNumber.swift, line 467

**Comment by bdlukaa** [comment]
Sorry but I'm unable to solve this issue because I don't have an apple environment. You can create a pull request. I think the cause if because we're parsing `params?["volume"]` as a `Float` but it comes as `NSNumber` from Flutter. The same with some other methods.

**Comment by bdlukaa** [comment]
This was fixed in the latest version: [v1.2.0](https://pub.dev/packages/native_admob_flutter)
