### ISSUE TITLE
Support for non-personalized ads

### ISSUE THREAD

**Issue by Skyost** [bdlukaa/native_admob_flutter#32]
Hey,

In some cases (like when a European user doesn't give its consent for some tracking cookies), it may be required to show only non-personalized ads. Would it be possible to add support for this in your plugin ?

I haven't checked your source code yet, some I cannot submit a pull request, but here are some links :

* [Android implementation](https://developers.google.com/admob/android/eu-consent#forward-consent).
* [iOS implementation](https://developers.google.com/admob/ios/eu-consent#forward-consent).

If you're okay and if you don't have the time to work on this, I may be able to send a pull request.

Thanks !

**Comment by bdlukaa** [comment]
The links you posted are the `legacy` ones, so they will no longer be valid in a near future. The current way to request authorization for users are in the documentation: 
- [Request App Tracking Tranparecy Authorization for iOS](https://github.com/bdlukaa/native_admob_flutter/wiki/Initialize#request-app-tracking-transparency-authorization-for-ios)
- [EU Consent 🔗](https://pub.dev/packages/admob_consent)
- [Complying with the Precise Location Data Policy](https://github.com/bdlukaa/native_admob_flutter/wiki/Complying-with-the-Precise-Location-Data-Policy)

Can this be closed?

**Comment by Skyost** [comment]
> [EU Consent 🔗](https://pub.dev/packages/admob_consent)

The biggest problem with this one, is that Funding Choices has a [big caveat](https://stackoverflow.com/questions/63583003/admob-tcf-error-when-using-google-ump-sdk) that stops ads from being served. Therefore the only workaround is to use that `npa` parameter. In fact, even Google added a such parameter in their brand new plugin (link [here](https://pub.dev/documentation/google_mobile_ads/latest/google_mobile_ads/AdRequest/nonPersonalizedAds.html)).

But that's up to you, it's your project after all 😁

**Comment by bdlukaa** [comment]
Hmm this is interesting. I've read the whole admob documentation, from top to bottom, and I never saw anyone ever mention the `nonPersonalizedAd`. I took a look at `google-mobile-ads` source and here's how they implement it:

Android:
```java
    if (nonPersonalizedAds != null && nonPersonalizedAds) {
      final Bundle extras = new Bundle();
      extras.putString("npa", "1");
      request.addNetworkExtrasBundle(AdMobAdapter.class, extras);
    }
```

iOS:
```swift
            let extras = GADExtras()
            extras.additionalParameters = ["npa": "1"]
            request.register(extras)
```

Tho I don't have a mac, so I can't implement the iOS part, it depends on the community. You can [join my discord server](https://discord.gg/674gpDQUVq) so we can talk better.
