### ISSUE TITLE
Reload/Refresh native ad when first ad is being shown. Is there any way to do it?

### ISSUE THREAD

**Issue by PravinNagargoje** [bdlukaa/native_admob_flutter#33]
I am currently showing a native ad on the home screen of the app. When the user goto the second screen and comes back to the home screen I want to refresh the previous ad. Is there any way by which I can achieve this using this framework?

One more question. Do I have to implement firebase_admob if I'm using this package? As firebase AdMob is being deprecated in April. Does this package support google_mobile_ads?

**Comment by bdlukaa** [comment]
> Do I have to implement firebase_admob if I'm using this package?

No it's not necessary.

> Does this package support google_mobile_ads?

I haven't tried, but some user have related incompatibilities with some admob plugins.

> When the user goto the second screen and comes back to the home screen I want to refresh the previous ad. Is there any way by which I can achieve this using this framework?

Yes. You can make use of a `NativeAdController`:

```dart
final controller = NativeAdController();

// build method
return NativeAd(controller: controller);

// push function
void navigateToOtherScreen() {
  await Navigator.push(context, OtherScreen());
  // use force: true, otherwise an message will be printed on the console saying there's already one ad available.
  controller.load(force: true);
}
```

Is it clear?

**Comment by PravinNagargoje** [comment]
Thank you for the explanation.
