### ISSUE TITLE
Version solving failed error

### ISSUE THREAD

**Issue by Tetracyl** [bdlukaa/native_admob_flutter#34]
Hi, I'm trying to use the latest version of this package (1.1.0) because it has the requestTrackingAuthorization method and has a bunch of bug fixes, however, I am getting this error: 

```Because my_app requires SDK version >=2.12.0 <3.0.0, version solving failed.
pub get failed (1; Because my_app requires SDK version >=2.12.0 <3.0.0, version solving failed.)
exit code 1
```

I think this error is happening because my project does not support null safety. I don't want to use the version without null safety (0.9.4) though since it doesn't have the requestTrackingAuthorization method nor the bug fixes. So what can I do?

**Comment by bdlukaa** [comment]
> So what can I do?

The only solution is to use null-safety. Almost all the pub packages now support null-safety, so you should migrate your app too.

**Comment by Skyost** [comment]
> I think this error is happening because my project does not support null safety. I don't want to use the version without null safety (0.9.4) though since it doesn't have the requestTrackingAuthorization method nor the bug fixes. So what can I do?

I think you're a bit stuck here. As you said, project needs to support null safety in order to be able to use the latest version of this plugin.

Another option for you would be to fork this project, an make your own non-null safety release. But please don't do that, all plugins are currently migrating to null safety, and it will be only a matter of time before you'll have to rewrite your project.

**Comment by Tetracyl** [comment]
I tried migrating to null safety a couple of weeks ago and had some issues because there were a few packages that I used that still haven't switched to null safety yet. I'll try migrating again though. Thank you.

**Comment by bdlukaa** [comment]
You can check if the dependencies now support null-safety by running `dart pub outdated --mode=null-safety`

For more info, read [this](https://dart.dev/null-safety/migration-guide)
