### ISSUE TITLE
Not all asset views lie inside the native ad view

### ISSUE THREAD

**Issue by a43501** [bdlukaa/native_admob_flutter#37]
Hi.

Please help. I've been trying to implement this package (native_admob_flutter: ^1.2.0) and running on an emulator, but I'm facing some weird log message:

I/Ads     ( 6336): Received log message: <Google:HTML> **Native ad view size has been detected to be 360x10.** This size seems to be too small, and might indicate a problem with your SDK implementation. Note that ad slots that have a width or height smaller than 32 will be demonetized in the future. Please make sure the ad view has sufficiently large area.

I/Ads     ( 6336): Received log message: <Google:HTML> **Not all asset views lie inside the native ad view.** This indicates an integration problem. Such implementations will not be supported in the future. Please make sure that all native ad assets are rendered inside the native ad view.

This is the code i have:

> 
    AdLayoutBuilder get adDefaultLayoutBuilder => (ratingBar, media, icon, headline,
        advertiser, body, price, store, attribution, button) {
      return AdLinearLayout(
        decoration: AdDecoration(backgroundColor: Color(0xFF111111)),
        width: MATCH_PARENT,
        height: MATCH_PARENT,
        orientation: HORIZONTAL,
        gravity: LayoutGravity.center_vertical,
        children: [
          //icon,
          AdLinearLayout(
            children: [icon],
            orientation: HORIZONTAL,
            width: WRAP_CONTENT,
            margin: EdgeInsets.symmetric(horizontal: 3),
          ),
          AdExpanded(
            flex: 2,
            child: AdLinearLayout(
              width: WRAP_CONTENT,
              margin: EdgeInsets.symmetric(horizontal: 3),
              children: [
                headline,
                AdLinearLayout(
                  orientation: HORIZONTAL,
                  children: [attribution, advertiser],
                ),
              ],
            ),
          ),
          AdExpanded(flex: 4, child: button),
        ],
      );
    };

> 
              bottomNavigationBar: Container(
                width: MediaQuery.of(context).size.width,
                color: primaryColor,
                height: _isBannerAdReady ? 60 : 10,
                child: NativeAd(
                  height: 60,
                  builder: (context, child) {
                    return Material(
                      elevation: 8,
                      child: child,
                    );
                  },
                  buildLayout: adDefaultLayoutBuilder,
                  loading: Text(''),
                  error: Text(''),
                  icon: AdImageView(padding: EdgeInsets.only(left: 6)),
                  headline: AdTextView(
                      style: TextStyle(
                    color: Colors.white.withOpacity(0.8),
                  )),
                  advertiser: AdTextView(
                      style: TextStyle(
                    color: Colors.white.withOpacity(0.7),
                  )),
                  body: AdTextView(
                      style: TextStyle(
                    color: Colors.white.withOpacity(0.8),
                  )),
                  media: AdMediaView(height: 70, width: 120),
                  attribution: AdTextView(
                    width: WRAP_CONTENT,
                    height: WRAP_CONTENT,
                    padding: EdgeInsets.symmetric(horizontal: 2, vertical: 0),
                    margin: EdgeInsets.only(right: 4),
                    maxLines: 1,
                    text: 'Ad',
                    decoration: AdDecoration(
                      borderRadius: AdBorderRadius.all(10),
                      border: BorderSide(color: Colors.black, width: 1),
                      backgroundColor: primaryColor,
                    ),
                    style: TextStyle(
                        color: Colors.white.withOpacity(0.8),
                        fontWeight: FontWeight.bold),
                  ),
                  button: AdButtonView(
                    width: WRAP_CONTENT,
                    height: WRAP_CONTENT,
                    padding: EdgeInsets.symmetric(horizontal: 6, vertical: 0),
                    margin: EdgeInsets.only(left: 0, right: 6),
                    //text: 'Learn More',
                    decoration: AdDecoration(
                      borderRadius: AdBorderRadius.all(30),
                      border: BorderSide(
                          color: Colors.white.withOpacity(0.9), width: 1),
                      backgroundColor: Color(0xFF111111),
                    ),
                    textStyle: TextStyle(
                      color: Colors.white.withOpacity(0.9),
                      fontSize: 14,
                      fontFamily: 'HelveticaNeueeText',
                    ),
                  ),
                ),
              ),

Thank you!

**Comment by bdlukaa** [comment]
Just make sure your ad is bigger than 32x32

> **Native ad view size has been detected to be 360x10**

The following line that is causing the issue:

```dart
height: _isBannerAdReady ? 60 : 10,
```

To solve this issue you can do:

```dart
bottomNavigationBar: _isBannerAdReady ? NativeAd(...) : Container(height: 10)
```

**Comment by a43501** [comment]
> Just make sure your ad is bigger than 32x32
> 
> > **Native ad view size has been detected to be 360x10**
> 
> The following line that is causing the issue:
> 
> ```dart
> height: _isBannerAdReady ? 60 : 10,
> ```
> 
> To solve this issue you can do:
> 
> ```dart
> bottomNavigationBar: _isBannerAdReady ? NativeAd(...) : Container(height: 10)
> ```

OMG! You're right! Problem solved. Thank you very much!
