### ISSUE TITLE
IOS build errors

### ISSUE THREAD

**Issue by Billy-80** [bdlukaa/native_admob_flutter#41]
The build fails for me on IOS with the build errors like these below. I have tried, cleaning but it doesn't help. Any suggestions?

Error output from Xcode build:

/.pub-cache/hosted/pub.dartlang.org/native_admob_flutter-1.2.0/ios/Classes/Interstitial/InterstitialAdController.swift:5:25: error: cannot find type 'GADInterstitialAd' in scope
pub.dartlang.org/native_admob_flutter-1.2.0/ios/Classes/Interstitial/InterstitialAdController.swift:29:13: error: cannot find 'GADInterstitialAd' in scope
.pub-cache/hosted/pub.dartlang.org/native_admob_flutter-1.2.0/ios/Classes/Interstitial/InterstitialAdController.swift:29:83: error: cannot find type 'GADInterstitialAd' in scope
.pub-cache/hosted/pub.dartlang.org/native_admob_flutter-1.2.0/ios/Classes/Native/NativeAdController.swift:4:37: error: cannot find type 'GADNativeAdLoaderDelegate' in scope
.pub-cache/hosted/pub.dartlang.org/native_admob_flutter-1.2.0/ios/Classes/Native/NativeAdController.swift:45:27: error: value of type 'GADNativeAd' has no member 'muteThisAd'
.pub-cache/hosted/pub.dartlang.org/native_admob_flutter-1.2.0/ios/Classes/Native/NativeAdView.swift:222:41: error: value of type 'GADNativeAd' has no member 'starRating'

**Comment by bdlukaa** [comment]
Are you using other admob dependencies?

**Comment by Billy-80** [comment]
No I also tried on another flutter project that I use for testing which has very few packages, same issue happens on that test project as well. Android builds ok . I am on Flutter 2.0.4

**Comment by bdlukaa** [comment]
Maybe related to https://github.com/bdlukaa/native_admob_flutter/issues/31#issuecomment-817197284

> Thank you. The problem was caused by me forgetting to run `pod install` in ios directory after adding this plugin to my pubspec.yaml.

**Comment by Billy-80** [comment]
It worked only after a pod update, the issue was caused by something on my side obviously. Thanks!

**Comment by bdlukaa** [comment]
Then this can be closed.
