### ISSUE TITLE
How to minimize lag when bannerads are loading? 

### ISSUE THREAD

**Issue by Wizzel1** [bdlukaa/native_admob_flutter#43]
I am using your package to place bannerads in a list view with the builder function but the app laggs while the ads are loading. Is there some sort of async method to decrease the lag?

**Comment by bdlukaa** [comment]
For banner ads, unfortuantely no. The ad needs to be on the screen so that it can be loaded.

But the lag should be minimal on release mode.

**Comment by Wizzel1** [comment]
I have also tested in in release mode. 
Even if its not that bad in releasemode it still keeps the listview from scrolling for about a second. 

Don't get me wrong, I know that is not your fault at all. I have tried the google_mobile_ads package and it is so bad that I get like 10 fps in release mode, so I am thankful for your package. 

Still don't understand why google gives us this unoptimized package that only runs smooth on high end devices and causes a bad experience for 80% of the users.

However. thanks for the quick reply.
