### ISSUE TITLE
[FEATURE REQUEST] Support targeting keywords in ad requests

### ISSUE THREAD

**Issue by kreativityapps** [bdlukaa/native_admob_flutter#47]

**Comment by bdlukaa** [comment]
Implemented this for Android in [1.3.0](https://pub.dev/packages/native_admob_flutter). iOS implementation is missing

**Comment by ramtinq** [comment]
Hi. Sorry for being so much late. I have done some implementations which I suppose should work. Please check this:

https://github.com/ramtinq/native_admob_flutter/tree/dev

But I don't have an active AdMob account to test if the ad content really changes based on the keywords used (I'm just currently using test ads).

**Comment by bdlukaa** [comment]
Feel free to make a pr.

**Comment by ramtinq** [comment]
Hi, did you check it?

**Comment by bdlukaa** [comment]
Published version 1.3.3 that is supposed to fix this issue
