### ISSUE TITLE
attaching controller to a NativeAd with VideoTestUnitId makes it load video-less ads

### ISSUE THREAD

**Issue by ramtinq** [bdlukaa/native_admob_flutter#49]
I'm not sure what's causing this but in your example app, by attaching controller to the last ad instead of the first one, makes the last ad to load video-less ads:

```
          if (controller.isLoaded)
          NativeAd(
            controller: controller,
            height: 320,
            unitId: MobileAds.nativeAdVideoTestUnitId,
```

**Comment by bdlukaa** [comment]
That's because, in initState, the controller loads the ad before the `NativeAd` is inserted to the tree. To load video ads with the controller, use `controller.load(unitId: MobileAds.nativeAdVideoTestUnitId);`
