### ISSUE TITLE
right open app ad implementation

### ISSUE THREAD

**Issue by devuserPP** [bdlukaa/native_admob_flutter#52]
Hi Guys,

Im quite new in flutter and Android development and not sure if I understand right way how to implement [app-open-ads](https://developers.google.com/admob/android/app-open-ads).  If I understand well, app open ads only show when users foreground my app.  According [documentation](https://github.com/bdlukaa/native_admob_flutter/wiki/Creating-an-app-open-ad), you always call `await appOpenAd.show()`  for showing open ad.  Can you please provide example how to achieve in flutter to show open ad when app goes to foreground?

**Comment by bdlukaa** [comment]
"The documentation thus far assumes that you only show app open ads when users foreground your app when it is suspended in memory.". You can check the app state in any stateful widget:

```dart
class _HomePageState extends State<HomePage> with WidgetsBindingObserver {
  // This variable will tell you whether the application is in foreground or not. 
  bool _isInForeground = true;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }
  
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    _isInForeground = state == AppLifecycleState.resumed;
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => Scaffold();
}
```

Check this stackoverflow answer: https://stackoverflow.com/a/64766900/11622876

I don't think this should be in the documentation since the code above is not part of the plugin.

**Comment by sunjianan9900** [comment]
hey , there's a thing, when after picking a picture, state = AppLifecycleState.resumed
after show other fullscreen ads , state == AppLifecycleState.resumed

**Comment by bdlukaa** [comment]
wdym?
