### ISSUE TITLE
android nonPersonalizedAds?

### ISSUE THREAD

**Issue by angelbuzon** [bdlukaa/native_admob_flutter#53]
Hi, on IOS, is clear but:

On android, where is indicated if the ad request is with nonPersonalizedAds?

**Comment by bdlukaa** [comment]
On Android, we use the [RequestFactory](https://github.com/bdlukaa/native_admob_flutter/blob/master/android/src/main/kotlin/com/bruno/native_admob_flutter/RequestFactory.kt) class to make the ad requests. The `nonPersonalizedAds` property is defined there.
