### ISSUE TITLE
Can't sync library on Xcode

### ISSUE THREAD

**Issue by nguyenlinhnttu** [bdlukaa/native_admob_flutter#54]
I can't sync library on Xcode version 12.2.
Android  working normal.
Please have a look:
https://ibb.co/GtDnB61

Thanks

**Comment by bdlukaa** [comment]
Maybe a duplicate of https://github.com/bdlukaa/native_admob_flutter/issues/41

**Comment by nguyenlinhnttu** [comment]
I use pod update and it working.
Closed.
