### ISSUE TITLE
Long initialization

### ISSUE THREAD

**Issue by mozerrr** [bdlukaa/native_admob_flutter#60]
It increased the loading time by 8-12 seconds on medium device (Xiaomi Mi A3).

**Comment by bdlukaa** [comment]
Can you try it in release mode?

**Comment by mozerrr** [comment]
It was in release mode and repeated on Xiaomi Redmi Note 4.

**Comment by bdlukaa** [comment]
You can try not awaiting the initialize method before `runApp`, and check if the sdk is initialized when loading the ads. If not, do not load or display the ads:

```dart
void main() {
   MobileAds.initialize();
}
```

**Comment by anisalibegic** [comment]
@mozerrr Did this solved your problem?
