### ISSUE TITLE
Error Message when run the example

### ISSUE THREAD

**Issue by erickcchoi** [bdlukaa/native_admob_flutter#61]
Please help, When start to run the example, console will show the error message below:
1. [ERROR:cookie_manager.cc(137)] Strict Secure Cookie policy does...
2. Exception thrown while unbinding...

Console :

> W/Ads     (18026): Not retrying to fetch app settings
W/Ads     (18026): Not retrying to fetch app settings
W/Ads     (18026): Not retrying to fetch app settings
E/chromium(18026): [ERROR:cookie_manager.cc(137)] Strict Secure Cookie policy does not allow setting a secure cookie for http://googleads.g.doubleclick.net/ for apps targeting >= R. Please either use the 'https:' scheme for this URL or omit the 'Secure' directive in the cookie value.
I/Ads     (18026): Received log message: <Google:HTML> Incorrect native ad response. Click actions were not properly specified
E/chromium(18026): [ERROR:cookie_manager.cc(137)] Strict Secure Cookie policy does not allow setting a secure cookie for http://googleads.g.doubleclick.net/ for apps targeting >= R. Please either use the 'https:' scheme for this URL or omit the 'Secure' directive in the cookie value.
I/Ads     (18026): Ad failed to load : 0
I/Ads     (18026): Received log message: <Google:HTML> Incorrect native ad response. Click actions were not properly specified
I/Ads     (18026): Ad failed to load : 0
W/ConnectionTracker(18026): Exception thrown while unbinding
W/ConnectionTracker(18026): java.lang.IllegalArgumentException: Service not registered: lm@d549f77
W/ConnectionTracker(18026): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1757)
W/ConnectionTracker(18026): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1874)
W/ConnectionTracker(18026): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:792)
W/ConnectionTracker(18026): 	at ce.b(:com.google.android.gms.dynamite_measurementdynamite@201817056@20.18.17 (040800-0):1)
W/ConnectionTracker(18026): 	at ce.a(:com.google.android.gms.dynamite_measurementdynamite@201817056@20.18.17 (040800-0):5)
W/ConnectionTracker(18026): 	at ln.A(:com.google.android.gms.dynamite_measurementdynamite@201817056@20.18.17 (040800-0):10)
W/ConnectionTracker(18026): 	at ky.a(:com.google.android.gms.dynamite_measurementdynamite@201817056@20.18.17 (040800-0):3)
W/ConnectionTracker(18026): 	at dy.run(:com.google.android.gms.dynamite_measurementdynamite@201817056@20.18.17 (040800-0):2)
W/ConnectionTracker(18026): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/ConnectionTracker(18026): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker(18026): 	at iw.run(:com.google.android.gms.dynamite_measurementdynamite@201817056@20.18.17 (040800-0):15)
E/chromium(18026): [ERROR:cookie_manager.cc(137)] Strict Secure Cookie policy does not allow setting a secure cookie for http://googleads.g.doubleclick.net/ for apps

**Comment by bdlukaa** [comment]
These are just warning. For load errors, see https://github.com/bdlukaa/native_admob_flutter/wiki/Ad-error-codes

**Comment by erickcchoi** [comment]
These error message is from the example code when run, please advice How to getrid of the warning.

> W/ConnectionTracker(24646): Exception thrown while unbinding
W/ConnectionTracker(24646): java.lang.IllegalArgumentException: Service not registered: lm@d58aabd
W/ConnectionTracker(24646): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1757)


> E/chromium(24646): [ERROR:cookie_manager.cc(137)] Strict Secure Cookie policy does not allow setting a secure cookie for http://googleads.g.doubleclick.net/ for apps targeting >= R. Please either use the 'https:' scheme for this URL or omit the 'Secure' directive in the cookie value.

**Comment by bdlukaa** [comment]
It doesn't hapeen on newer devices. See https://github.com/firebase/firebase-android-sdk/issues/1662#issuecomment-744603267

**Comment by bdlukaa** [comment]
> The warning is benign and is safe to ignore. The fix will get rolled out around Feb 2021, no action is required on developers' side, the fix will apply to google play services itself and existing apps will stop generating the warning.
