### ISSUE TITLE
Adding TestDeviceIds vs adding the IDFA in Admob

### ISSUE THREAD

**Issue by Wizzel1** [bdlukaa/native_admob_flutter#62]
So I am currently setting the TestDeviceIds but for every ad, I am getting 
```
I/Ads     (31847): This request is sent from a test device.
I/Ads     (31847): Ad failed to load : 3
```
so I am seeing no ads at all. I noticed that there is another option on AdMob itself to ad a test device by Advertising ID/IDFA. 

So what's the preferred way and the difference?

**Comment by bdlukaa** [comment]
https://github.com/bdlukaa/native_admob_flutter/wiki/Ad-error-codes#load-error-codes

The request was successful, but no ad was returned due to lack of ad inventory

**Comment by Wizzel1** [comment]
Thanks, but that only partially answers my question. What is the difference between those two options?

**Comment by bdlukaa** [comment]
There's no such difference
