### ISSUE TITLE
Semi-transparent background of native ad view ios

### ISSUE THREAD

**Issue by mozerrr** [bdlukaa/native_admob_flutter#65]
https://github.com/bdlukaa/native_admob_flutter/blob/61a8d3c58c3470bdfc87b8acc1d7b586cac9aa32/ios/Classes/Native/NativeAdView.swift#L28
Why background color of NativeAdView isn't fully transparent? Could i change to transparent?

**Comment by bdlukaa** [comment]
Native Ads on iOS isn't fully supported, as stated on the documentation. Please see #58

**Comment by mozerrr** [comment]
#66 released fix
