### ISSUE TITLE
[iOS] [NativeAd] <Google> User interactions must be disabled on the asset view to enable click handling. userInteractionEnabled has been set to NO on <UIButton: 0x7f8bd44caa10; frame = (0 0; 0 0); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x600000c02560>>.

### ISSUE THREAD

**Issue by ramtinq** [bdlukaa/native_admob_flutter#69]
This warning is shown in iOS devices for each NativeAd which has a button:
`<Google> User interactions must be disabled on the asset view to enable click handling. userInteractionEnabled has been set to NO on <UIButton: 0x7f8bd44caa10; frame = (0 0; 0 0); opaque = NO; userInteractionEnabled = NO; layer = <CALayer: 0x600000c02560>>`

**Comment by Tetracyl** [comment]
I was also getting this warning

**Comment by bdlukaa** [comment]
Published version 1.3.3 that is supposed to fix this issue
