### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by FatihTirek** [bdlukaa/native_admob_flutter#75]
I made an app and it's almost ready but I have some questions about ads (As a beginner):

1-) Is rewarded app always loading when I call load() function or is there any cooldown? The reason I'm asking that is I have a lot of customizations for app ui like theme, shape etc. and I'm planning opening them by one-time ad watch and if there any cooldown for that I'm gonna notify user about this.

2-) Is Native ads changing their content spontaneously or should I done that by calling load() function with a Timer?

**Comment by bdlukaa** [comment]
1) Rewarded ad immediatally loads the ad if any other hasn't been loaded yet. If it has, you need to use `load(force: true)`

2) Unlike BannerAds, NativeAds does not change its content. It's necessary to reload the ad (`load(force: true)`) in order to load a new ad.

**Comment by FatihTirek** [comment]
@bdlukaa Thanks for reply. One more thing how can I pass custom value to rewardAd to get that value when earn callback fired?

**Comment by bdlukaa** [comment]
You can't.
