### ISSUE TITLE
Server Side Verification (SSV) - Information

### ISSUE THREAD

**Issue by sageata** [bdlukaa/native_admob_flutter#77]
Thank you for the package, @bdlukaa!

Is there any chance to add  ```userId``` as a parameter in the ```load``` function  in order to enable SSV?

This would be needed for both ```rewadedAd``` and ```rewardedInterstitialAd```

**Comment by bdlukaa** [comment]
Useful links:
- https://developers.google.com/admob/android/ssv
- https://developers.google.com/admob/ios/ssv

This would be a good pr.

**Comment by sageata** [comment]
@bdlukaa, I created a PR for this.

Please check this: #78
