### ISSUE TITLE
how can I find out if the ad is shown in the widget?

### ISSUE THREAD

**Issue by FetFrumos** [bdlukaa/native_admob_flutter#80]
I am displaying ads in my application (in the form of cards). I can get event from controller

but the user can immediately swipe away the ad card. how can I check if an ad is shown for a few seconds?

there is an event - loaded, and I need to do something - "shown". How can I do this. any ideas?

**Comment by bdlukaa** [comment]
We used to have the `impression` event on this plugin, but it was removed.

https://developers.google.com/android/reference/com/google/android/gms/ads/AdListener#onAdImpression()

**Comment by FetFrumos** [comment]
Thank you, I close this issue
