### ISSUE TITLE
[Question] Is there any way to determine wether NativeAd's PlatformView is ready to be displayed?

### ISSUE THREAD

**Issue by ramtinq** [bdlukaa/native_admob_flutter#82]
In iOS, something like this works perfectly to show the ad immediately after it's ready:

```
return Opacity( opacity: _controller.isAttached ? 1 : 0,
                           child: NativeAd(
                                         controller: _controller,
                                          builder: (context, child) {
                                            return Material(
                                              color: Colors.blue,
                                              child: child,
                                            );
                                          },
                                          ...)
                         );

```

This will make the ad to appear immediately after isAttached becomes true, just as fast as a flutter widget, without any flashing / empty blue space before ad contents are displayed. However in Android, Builder's blue area shows up, and after some milliseconds the ad content show up. This is what happens in iOS without the use of `_controller.isAttached`. It seems that in iOS `isAttached` is the correct indicator of the widget being ready to be displayed immediately, but in Android it's not. I wanted to know if there could be any other way to determine if the ad's platformView is already loaded and can be displayed immediately. I could work on it if you have any idea, because I'm not expert on platformViews.
Thanks.

**Comment by ramtinq** [comment]
I just looked at the platform_views.dart file and I just found out there's some intentional delay added for Android in these lines:

```
          // This is the current fix for this issue:
          // https://github.com/bdlukaa/native_admob_flutter/issues/11
          await Future.delayed(widget.delayToShow ?? kDefaultAndroidViewDelay);
```
is it the reason for the problem I explained above?

And is it still necessary for solving https://github.com/bdlukaa/native_admob_flutter/issues/11 ?

**Comment by bdlukaa** [comment]
> is it the reason for the problem I explained above?

yes

> And is it still necessary for solving #11 ?

yes. On Android is necessary (see https://github.com/flutter/flutter/issues/39797). But you can set `delayToShow` to `Duration.zero` to get no delay, but the issue reported in #11 will be show
