### ISSUE TITLE
[Question] Native ads guidelines (AdChoices or Ads by Google Icon) 

### ISSUE THREAD

**Issue by EternalYouth29** [bdlukaa/native_admob_flutter#83]
Hi, according to Google AdMob [Native ads policies & guidelines](https://support.google.com/admob/answer/6329638), it is required to display **'Ad Attribution'** and **'AdChoices icon (or Ads by Google, where applicable)'**. 
In the [Screenshots](https://github.com/bdlukaa/native_admob_flutter/wiki/Creating-a-native-ad) of the ads, the **'Ads by Google'** is showing on the top right corner, but I am not able to find this **'AdChoices'** attribute in the [example](https://github.com/bdlukaa/native_admob_flutter/blob/master/example/lib/screens/native_ads.dart) code.

May I know is the **'AdChoices icon (or Ads by Google)'** required when implementing native ads? If yes, how do I enable it? 

Thanks.

**Comment by bdlukaa** [comment]
it is implemented by default by admob. all you can do is to position the ad choices button in any of the four corners of the ad

**Comment by EternalYouth29** [comment]
> it is implemented by default by admob. all you can do is to position the ad choices button in any of the four corners of the ad

Thanks for the info. May I know how do I position the ad choices button? I couldn't find this attribute name in Example code.

**Comment by EternalYouth29** [comment]
> it is implemented by default by admob. all you can do is to position the ad choices button in any of the four corners of the ad

I followed the example code but the ad choices icon doesn't show up in my test ads. Does it mean that I don't have to worry about that and leave it to admob to handle it?

**Comment by bdlukaa** [comment]
you can set the native ad options.

See https://github.com/bdlukaa/native_admob_flutter/wiki/Native-Ad-Options#adchoichesplacement

**Comment by EternalYouth29** [comment]
> you can set the native ad options.
> 
> See https://github.com/bdlukaa/native_admob_flutter/wiki/Native-Ad-Options#adchoichesplacement

Thanks a lot for the help :)

**Comment by gadgetreviews** [comment]
I added ADCHOICES_TOP_RIGHT and reloadWhenOptionsChange = false, but I still can't see AdChoices in test ads. Is this because this is a test ad?

```
    nativeAd = NativeAd(
      reloadWhenOptionsChange: false,
      buildLayout: adBannerLayoutBuilder,          
      options: NativeAdOptions(
        adChoichesPlacement: NativeAdOptions.ADCHOICES_TOP_RIGHT,
      ),
...
```

**Comment by EternalYouth29** [comment]
> 
> 
> I added ADCHOICES_TOP_RIGHT and reloadWhenOptionsChange = false, but I still can't see AdChoices in test ads. Is this because this is a test ad?
>

`Admob` will take care of that in production.

**Comment by gadgetreviews** [comment]
> > I added ADCHOICES_TOP_RIGHT and reloadWhenOptionsChange = false, but I still can't see AdChoices in test ads. Is this because this is a test ad?
> 
> `Admob` will take care of that in production.

Are you sure? I don't want my app rejected just for this. Also my admob account might have strike for policy violation. It would be better If I can see where AdChoices will be placed in test mode.

**Comment by gadgetreviews** [comment]
I found this information

**Key Point: These demo ad units are configured to serve direct-sold ads in Ad Manager, and direct-sold ads do not return AdChoices.**

from this link:
https://developers.google.com/ad-manager/mobile-ads-sdk/ios/test-ads

This means we will not see AdChoices at test mode.

**Comment by EternalYouth29** [comment]
> Are you sure? I don't want my app rejected just for this. Also my admob account might have strike for policy violation. It would be better If I can see where AdChoices will be placed in test mode.

To safely test production ads, you can setup your test device in your `Admob` account. 
https://support.google.com/admob/answer/9691433#example

You will be able to see `AdChoices` once you release Internal testing.
