### ISSUE TITLE
BorderRadius doesn't affect media

### ISSUE THREAD

**Issue by naamapps** [bdlukaa/native_admob_flutter#86]
Hey,
I'm trying to add border radius to the media but it doesn't work:
```
media: AdMediaView(
        decoration: AdDecoration(
          borderRadius: AdBorderRadius.all(10),
        ),
      ),
```
Also tried wrapping the NativeAd in ClipRRect, it also didn't work.

Please advise,
Thanks.

**Comment by bdlukaa** [comment]
You can't apply a border radius to asset views, such as `AdMediaView` or `AdIconView`

**Comment by naamapps** [comment]
Understandable, Thanks 👍
