### ISSUE TITLE
iOS implementation requires Android embedding v2

### ISSUE THREAD

**Issue by jakesq** [bdlukaa/native_admob_flutter#9]
Trying to run on an iOS 14 device, I receive the following message:

`The plugin native_admob_flutter requires your app to be migrated to the Android embedding v2. Follow the steps on https://flutter.dev/go/android-project-migration and re-run this command.
Exited (1)
`

If this package supports both Android and iOS, why do I need to include Android embedding support?
Is this something that will change as the package matures?

**Comment by bdlukaa** [comment]
iOS is NOT supported: https://github.com/bdlukaa/native_admob_flutter/wiki/Platform-setup#ios
> iOS is currently not supported (I don't have an Apple environment :/).

But it's weird that you're trying to run on iOS and it says something about android. But either way, it's necessary to migrate to embeeding v2 to use this plugin on Android.

**Comment by jakesq** [comment]
Ah okay, thanks for the clarification. 

I assumed iOS was supported as it states so on the pub.dev page, I'd recommend changing that :)

**Comment by bdlukaa** [comment]
Removed the iOS label from pub and added the supported platforms on readme :) (v[0.9.1+1](https://pub.dev/packages/native_admob_flutter))

**Comment by bdlukaa** [comment]
iOS is now supported! It supports Banner, Interstitial, Banner and App Open Ads. [v1.0.0](https://pub.dev/packages/native_admob_flutter)

**Comment by jakesq** [comment]
That's awesome to hear!  I'll let you know if I have any issues. :)
