### ISSUE TITLE
[IOS] Layout shift

### ISSUE THREAD

**Issue by soulbalz** [bdlukaa/native_admob_flutter#90]
I found an issue with BannerAd that have an layout shift on IOS please see on my attachment
![IMG_9626](https://user-images.githubusercontent.com/10706704/126447256-afe5584a-d659-44a2-9003-d1028ce72d3b.PNG)
![IMG_9627](https://user-images.githubusercontent.com/10706704/126447286-334504c9-64c2-447c-ad90-e96657728f2f.PNG)

**Comment by bdlukaa** [comment]
@soulbalz this is likely fixed on the latest Flutter version and is not an issue with the package.

**Comment by soulbalz** [comment]
> @soulbalz this is likely fixed on the latest Flutter version and is not an issue with the package.

Hi, I have tested on the latest version of native_admob_flutter (the latest is 1.5.0) and it's still not fix.
