### ISSUE TITLE
Crash log

### ISSUE THREAD

**Issue by ovaldi** [bdlukaa/native_admob_flutter#93]
Hi @bdlukaa   it seems there is a issue as below:

![image](https://user-images.githubusercontent.com/4537336/128503020-64a928fa-1d41-41ce-87b0-fee6d745e0d0.png)

Devices: **Galaxy Note9 (Android 10)** &  **Honor V20 (Android 8)**

**Comment by bdlukaa** [comment]
Duplicate of #91
