### ISSUE TITLE
where to put the unitId

### ISSUE THREAD

**Issue by tudosxxx** [bdlukaa/native_admob_flutter#95]
MobileAds.initialize(
    rewardedInterstitialAdUnitId: 'ca-app**********'
  );

final rewardedInterstitial = RewardedInterstitialAd(unitId?)..load(unitId?)；

**Comment by tudosxxx** [comment]
Put the correct id, the load() method returns false, and the test advertisement can still be opened during the test. Is there a problem with this?

**Comment by bdlukaa** [comment]
whenever in debug mode (or running on emulator), you'll get test ads.

Either way, I recommend you to use test ads when in debug mode (see the example app).

For rewarded ad, you can define an unit I'd for all the rewarded ads in `MobileAds.initialize`, or a separated one on the RewardedAd constructor
