### ISSUE TITLE
Fail to set Admob appID programmatically.

### ISSUE THREAD

**Issue by erickcchoi** [bdlukaa/native_admob_flutter#96]
Fail to set admob app ID in MobileAds.initialize(this, "YOUR_ADMOB_APP_ID"),

Please advice how to set admob app ID programmatically. instead of under AndroidManifest.xml .

Thank you very much for your help.

**Comment by bdlukaa** [comment]
This is not possible and this function was depreciated in native as well.

**Comment by erickcchoi** [comment]
Please advice, Is any other way to change the admob app ID instead of a fixed admob app ID ?

**Comment by bdlukaa** [comment]
Unfortunately no :/

https://stackoverflow.com/questions/61577107/how-to-set-admob-appid-programmatically-19-1-0
